# Do not modify this file! It was generated by ‘nixos-generate-config’
# Installer-safe Raspberry Pi / CM4 hardware config
{ lib, ... }:

{
  # imports = [
  #   (modulesPath + "/installer/scan/not-detected.nix")
  #   (modulesPath + "/installer/sd-card/sd-image-aarch64-installer.nix")
  # ];

  boot.kernelParams = [
    "quiet"
    "loglevel=3"
  ];

  boot.extraModprobeConfig = lib.mkAfter ''
    options brcmfmac p2p_enable=0
  '';

  # # Firmware needed for Wi-Fi, GPU, etc.
  # hardware.enableRedistributableFirmware = true;

  # # Let the Pi firmware handle DT selection
  # hardware.deviceTree.enable = true;

  # # Serial console is correct for installer debugging
  # boot.kernelParams = [
  #   "console=ttyAMA0,115200"
  #   "console=tty1"
  # ];

  # # DHCP is fine for installer
  # networking.useDHCP = lib.mkDefault true;

  # # Platform
  # nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";

  # # Keep filesystem support minimal
  # boot.supportedFilesystems = lib.mkForce [
  #   "ext4"
  #   "btrfs"
  # ];
}
