# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:
let
  system = "aarch64-linux";
in
{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp49s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault system;
  nixpkgs.config.allowUnsupportedSystem = false;
  
  # ARM-specific settings - no Intel microcode on ARM!
  # hardware.cpu.intel.updateMicrocode is not applicable for ARM
}

