# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot = {
    extraModulePackages = [ ];

    initrd = {
      availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
      kernelModules = [ ];
      systemd.dbus.enable = false;
      systemd.enable = false;
    };

    kernelModules = [ "kvm-intel" ];

    loader.efi.canTouchEfiVariables = true;
    loader.systemd-boot.enable = true;

    tmp.cleanOnBoot = true;
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/48d6e801-07b3-4034-9cfe-4eb4e8ba10a6";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/B770-7B4F";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/0c8203ff-b8be-4907-afb5-84fa6fb151c4";
    fsType = "ext4";
    options = [ "noatime" ];
  };

  fileSystems."/bucket" = {
    device = "/dev/disk/by-uuid/8cce772f-7b2e-45b1-9cb7-4d9d17161f13";
    fsType = "ext4";
    options = [ "noatime" ];
  };

  fileSystems."/ollama" = {
    device = "/dev/disk/by-uuid/f240624a-177f-4da0-834b-5fb2c0de63a8";
    fsType = "ext4";
    options = [ "noatime" ];
  };

  swapDevices = [ ];

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;

  hardware.graphics = {
    enable = true;
    enable32Bit = true; # for 32-bit applications
  };

  powerManagement = {
    cpuFreqGovernor = "performance";
    enable = true;
  };

  boot.plymouth.enable = false;
}
