#alias fuck='sudo $(history -p \!\!)'
#eval $(thefuck --alias)

alias cdh="cd ~"
alias ci3="cd ~/.config/i3"
alias cnix="cd /etc/nixos"
alias browse="nautilus --browser . &"
alias vi="vim -v"
alias vim="vim -v"
alias v="vim -v"
alias vv="vim -v ."
alias vi3="vim -v ~/.config/i3/config"
alias valias="vim -v ~/.bash_aliases"
alias vssh="vim -v ~/.ssh/config"
alias vfz='vim -v $(fzf)'


# alias l="ls"
alias inspireme="fortune | cowsay | lolcat"
alias git-fix="git submodule sync --recursive; git submodule update --init --recursive"
alias src="source ~/.bashrc"
# Stop all containers
dstop() { docker stop $(docker ps -a -q); }

alias dockerNuke="dstop"

alias salias='source ~/.bash_aliases'
alias vbashrc='vim -v ~/.bashrc'
alias vrc="vim -v ~/.vimrc"

alias please='sudo'
fmkcd() { mkdir -p "$1" && cd "$1"; }
alias mkcd='fmkcd'
alias here='i3-sensible-terminal &'
alias untar='tar -xf'

alias nload="nload -u H enp2s0"
alias edit-macros="code ~/.config/macro-app/config.json"
alias fixmouse="sudo systemctl restart g600.service && i3-msg restart"

alias iosinstall="ideviceinstaller -i"
alias ga="git add"
alias gaa="git add ."
alias gai="git add -ip"
alias gpl="git pull"
alias gd="git diff"
alias gds="git diff --staged"
alias gc="git commit --verbose"
alias gcf="git commit -m 'fix'"
alias gca="git commit --amend --verbose"
alias gp="git push --all"
alias gs="git status"
alias gwt="git worktree list"
alias gpt='git push origin $(git rev-parse --abbrev-ref HEAD)'
alias gco='git checkout --ignore-other-worktrees'
alias gsc="git submodule sync --recursive; git submodule update --init --recursive"
alias gf="git fetch-all"
alias cg='cd $(git root)'
alias grc="git rebase --continue"
alias vg="vim +':Git mergetool'"
alias gus="git restore --staged -- "
gcop() {
  git checkout refs/pull/$1/head
}
gn() {
  git checkout -b dan/$1
}
alias gnl="git nicelog"
alias gaagc="git add . && git commit -a --verbose"


alias listpaths="echo $PATH | sed \"s/:/\n/g\""

alias licenses="license-report --output=html | hcat"
function copy() {
  cat $1 | xsel -i -b
}
alias xmerge="xrdb -merge ~/.Xresources && xrdb -merge ~/.Xdefaults"
alias dc="docker-compose"
# alias gvim -vrc="vim ~/.vimrc"
alias open="xdg-open"
alias capcpu="sudo cpulimit --limit 1200 -iz -p $(ps -eo %cpu,pid --sort -%cpu | head -n2 | tail -n1 | awk '{{print $2}}')"
alias capProc="sudo cpulimit --limit 1200 -iz -p "

alias clip="xclip -selection c"
alias upgrade-dashboard="kubectl rollout restart -n default deployment lime-dashboard"
alias screen-normal="source ~/.screenlayout/normal.sh"
alias screen-lime="source ~/.screenlayout/lime.sh"
alias cfzf='cd "$(dirname $(fzf))"'
alias tf="terraform"
alias rmr="rm -r"
alias tn="textnote"
alias edithosts="sudo vim /etc/hosts"
alias c="cat"
alias d="docker"
alias lg="lazygit"

alias tfa="terraform apply"
alias tfaa="terraform apply --auto-approve"
alias tfd="terraform destroy"
alias tfdd="terraform destroy --auto-approve"
alias tfp="terraform plan"
alias tfi="terraform init"

docker-send() {
  docker save $1 | ssh -C $2 docker load
}

alias zadd="zoxide add"
alias r="ranger-cd"
alias npmi="npm install"
