[tf2]
ON_ACTIVATE="/home/dan/.config/g600.conf.d/onchange.sh ff0000"
G9_DOWN="xdotool key 2"
G10_DOWN="xdotool key 1"
G11_DOWN="xdotool key 3"
G12_DOWN="xdotool key e"
G13_DOWN="xdotool key r"
G14_DOWN="xdotool key q"
G15_DOWN="xdotool key F2"
G16_DOWN="xdotool key F1"
G17_DOWN="xdotool key p"
G18_DOWN="xdotool key x"
G19_DOWN="xdotool key z"
G20_DOWN="xdotool key a"
G10_DOWN_MOD="/home/dan/.config/g600/tf2/tf2_eureka_escape.sh 1"
G11_DOWN_MOD="/home/dan/.config/g600/tf2/tf2_eureka_escape.sh 2"
G12_DOWN_MOD="/home/dan/.config/g600/tf2/tf2_spy.sh"
G14_DOWN_MOD="xdotool key F1"
G15_DOWN_MOD="playerctl previous"
G16_DOWN_MOD="playerctl play-pause"
G17_DOWN_MOD="playerctl next"
G9_DOWN_MOD="/home/dan/.config/g600/tf2/tf2_create_sentry.sh"

[overwatch]
ON_ACTIVATE="/home/dan/.config/g600.conf.d/onchange.sh fcba03"
G9_DOWN="xdotool key v"
G10_DOWN="xdotool key r"
G11_DOWN="xdotool key e"
G12_DOWN="xdotool key x"
G14_DOWN="xdotool key z"
G16_DOWN="xdotool key Control_L+dead_grave"
G10_DOWN_MOD="xdotool key r"
G11_DOWN_MOD="xdotool key shift"
